### ISSUE TITLE
Language Filter Whitelist

### ISSUE THREAD

**Issue by Shiftyfish87** [DuncanCasteleyn/DiscordModBot#24]
Introduce a whitelist function to the language filter.

Some terms like "tard" make sense to place under the "ends with" filter as it's often use as a suffix to insult users.

However this can cause issues where a word like "bastard" will be flagged for removal. Being able to create a whitelist for specific exceptions would be very helpful in that regard

**Comment by DuncanCasteleyn** [comment]
Discord has provided their own integrated solution for this making this solution redundant.
