### ISSUE TITLE
#rezero_news WN chapter announcement feature 

### ISSUE THREAD

**Issue by SoSaSeSo** [DuncanCasteleyn/DiscordModBot#25]
The idea that was previously discussed: 

Once there has been an update of a certain size (~4k characters) to Tappei's WN site ( https://ncode.syosetu.com/n2267be/ )  the bot leaves a message in the rezero_news channel saying there was an update. 

Once the chapter gets published the bot posts the link to the chapter in the channel with a message and pings the WN updates role.

**Comment by DuncanCasteleyn** [comment]
Will be done in a seperate project
